project:
  type: book
  output-dir: docs

book:
  title: "K-Means Clustering and Its Place In Ecommerce"
  author:
    - name: Addison Armstrong
      affiliations:
        - name: University of West Florida
    - name: Alesha Bolin
      affiliations:
        - name: University of West Florida
    - name: Chandan Reddy Yapala
      affiliations:
        - name: University of West Florida
  date: "12/1/2023"
  page-navigation: true
  chapters:
    - index.qmd
    - Methods.qmd
    - Methods2.qmd
    - Methods3.qmd
    - analysis.qmd
    - Conclusion.qmd
    - FutureWorks.qmd
  appendices:
    - references.qmd
    - all_code.qmd

bibliography: references.bib
csl: http://www.zotero.org/styles/ieee

format:
  html:
    theme: cosmo
    df-print: paged
    code-fold: true

editor: visual