project:
  type: book
  output-dir: docs

book:
  title: "K-Means Clustering and Its Place In Ecommerce"
  author:
    - name: Addison Armstrong
      affiliations:
        - name: University of West Florida
    - name: Alesha Bolin
      affiliations:
        - name: University of West Florida
    - name: Chandan Reddy Yapala
      affiliations:
        - name: University of West Florida
  date: "12/1/2023"
  page-navigation: true
  chapters:
    - index.qmd
    - part: "The Method"
      chapters:
        - Methods.qmd
        - Methods2.qmd
        - Methods3.qmd
    - part: "E-commerce Analysis"
      chapters:
        - analysis.qmd
        - Conclusion.qmd
        - FutureWorks.qmd
  appendices:
    - references.qmd
    - K-MeansPresentation.qmd
    - all_code.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: paged
    code-fold: true

editor: visual