project:
  type: book

book:
  title: "K-Means-Quarto"
  author: "Addison Armstrong, Alesha Bolin, Chandan Reddy Yapala"
  date: "9/27/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - Methods.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

