project:
  type: book
  output-dir: docs

book:
  title: "K-Means Clustering And Its Place in Ecommerce"
  author: "Addison Armstrong, Alesha Bolin, Chandan Reddy Yapala"
  date: "9/27/2023"
  page-navigation: true
  chapters:
    - index.qmd
    - part: "The Method"
      chapters:
        - Methods.qmd
        - Methods2.qmd
        - Methods3.qmd
    - part: "E-commerce Analysis"
      chapters:
        - analysis.qmd
  appendices:
    - references.qmd

bibliography: references.bib

format:
  html: 
    theme: cosmo

editor: visual