project:
  type: book

book:
  title: "K-Means Clustering And Its Place in Ecommerce"
  author: "Addison Armstrong, Alesha Bolin, Chandan Reddy Yapala"
  date: "9/27/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - Methods.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    embed-resources: true
    self-contained-math: true
  pdf:
    documentclass: scrreprt

editor: visual